apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicas  }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}-project
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}-project
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.containerPort }}
